export const mockRecipes = [
  {
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    image: "https://img.spoonacular.com/recipes/716429-556x370.jpg",
    imageType: "jpg",
    servings: 2,
    readyInMinutes: 45,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
    aggregateLikes: 209,
    healthScore: 18,
    spoonacularScore: 84.0,
    pricePerServing: 163.15,
    cheap: false,
    creditsText: "Full Belly Sisters",
    license: "CC BY 3.0",
    sourceName: "Full Belly Sisters",
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 15,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["mediterranean"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["lacto ovo vegetarian"],
    occasions: [],
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "solid",
        name: "butter",
        nameClean: "butter",
        original: "1 Tbsp butter",
        originalName: "butter",
        amount: 1.0,
        unit: "Tbsp",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 14.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11135,
        aisle: "Produce",
        image: "cauliflower.jpg",
        consistency: "solid",
        name: "cauliflower florets",
        nameClean: "cauliflower florets",
        original: "2 cups frozen cauliflower florets",
        originalName: "frozen cauliflower florets",
        amount: 2.0,
        unit: "cups",
        meta: ["frozen"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 200.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "5 cloves garlic",
        originalName: "garlic",
        amount: 5.0,
        unit: "cloves",
        meta: [],
        measures: {
          us: { amount: 5.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 5.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 20420,
        aisle: "Pasta and Rice",
        image: "fusilli.jpg",
        consistency: "solid",
        name: "pasta",
        nameClean: "pasta",
        original: "6 ounces pasta",
        originalName: "pasta",
        amount: 6.0,
        unit: "ounces",
        meta: [],
        measures: {
          us: { amount: 6.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 170.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "solid",
        name: "scallions",
        nameClean: "scallions",
        original: "3 green white scallions",
        originalName: "green white scallions",
        amount: 3.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 18064,
        aisle: "Bakery/Bread",
        image: "breadcrumbs.jpg",
        consistency: "solid",
        name: "bread crumbs",
        nameClean: "bread crumbs",
        original: "1/4 cup whole wheat bread crumbs",
        originalName: "whole wheat bread crumbs",
        amount: 0.25,
        unit: "cup",
        meta: ["whole wheat"],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 30.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Melt the butter in a large skillet over medium heat. Add the breadcrumbs and toast until golden, about 3-4 minutes. Remove and set aside.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 18064,
                name: "bread crumbs",
                localizedName: "bread crumbs",
                image: "breadcrumbs.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 2,
            step: "Cook the pasta according to package directions. Reserve 1 cup of pasta water before draining.",
            ingredients: [
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "In the same skillet, sauté garlic, scallion whites, and cauliflower until caramelized. Deglaze with white wine if using. Season with salt, pepper, and red pepper flakes.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11291,
                name: "scallions",
                localizedName: "scallions",
                image: "spring-onions.jpg",
              },
              {
                id: 11135,
                name: "cauliflower florets",
                localizedName: "cauliflower florets",
                image: "cauliflower.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 4,
            step: "Toss the drained pasta with the cauliflower mixture, adding pasta water as needed. Top with toasted breadcrumbs and scallion greens. Serve immediately.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    instructions:
      "Melt the butter in a large skillet over medium heat. Add the breadcrumbs and toast until golden. Cook the pasta, reserving some pasta water. Sauté garlic, scallion whites and cauliflower. Combine everything and top with breadcrumbs.",
  },
  {
    id: 715538,
    title: "What to Make for Dinner Tonight?? Bruschetta Style Pork & Pasta",
    image: "https://img.spoonacular.com/recipes/715538-556x370.jpg",
    imageType: "jpg",
    servings: 4,
    readyInMinutes: 35,
    sourceUrl: "https://www.pinkwhen.com/bruschetta-style-pork-pasta/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/what-to-make-for-dinner-tonight-bruschetta-style-pork-pasta-715538",
    aggregateLikes: 23,
    healthScore: 45,
    spoonacularScore: 92.0,
    pricePerServing: 287.42,
    cheap: false,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["mediterranean", "italian"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    extendedIngredients: [
      {
        id: 10023572,
        aisle: "Meat",
        image: "fresh-pork.png",
        consistency: "solid",
        name: "pork tenderloin",
        nameClean: "pork tenderloin",
        original: "1 lb pork tenderloin",
        originalName: "pork tenderloin",
        amount: 1.0,
        unit: "lb",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "lb", unitLong: "pound" },
          metric: { amount: 453.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11529,
        aisle: "Produce",
        image: "tomato.png",
        consistency: "solid",
        name: "tomatoes",
        nameClean: "tomato",
        original: "2 cups diced tomatoes",
        originalName: "diced tomatoes",
        amount: 2.0,
        unit: "cups",
        meta: ["diced"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 360.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "3 cloves garlic, minced",
        originalName: "garlic",
        amount: 3.0,
        unit: "cloves",
        meta: ["minced"],
        measures: {
          us: { amount: 3.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 3.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 20420,
        aisle: "Pasta and Rice",
        image: "spaghetti.jpg",
        consistency: "solid",
        name: "pasta",
        nameClean: "pasta",
        original: "8 oz pasta",
        originalName: "pasta",
        amount: 8.0,
        unit: "oz",
        meta: [],
        measures: {
          us: { amount: 8.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 226.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Season and sear the pork tenderloin until cooked through. Rest and slice.",
            ingredients: [
              {
                id: 10023572,
                name: "pork tenderloin",
                localizedName: "pork tenderloin",
                image: "fresh-pork.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 2,
            step: "Cook pasta according to package directions.",
            ingredients: [
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "spaghetti.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Sauté garlic and tomatoes to make a quick bruschetta-style sauce. Toss with pasta and sliced pork.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11529,
                name: "tomatoes",
                localizedName: "tomatoes",
                image: "tomato.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    instructions:
      "Season and cook the pork. Prepare pasta. Make a quick tomato-garlic sauce and combine everything.",
  },
  {
    id: 644387,
    title: "Garlicky Kale",
    image: "https://img.spoonacular.com/recipes/644387-556x370.jpg",
    imageType: "jpg",
    servings: 2,
    readyInMinutes: 15,
    sourceUrl: "https://www.foodista.com/recipe/J2FTX87W/garlicky-kale",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/garlicky-kale-644387",
    aggregateLikes: 19,
    healthScore: 92,
    spoonacularScore: 98.0,
    pricePerServing: 69.23,
    cheap: true,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: "no",
    ketogenic: false,
    whole30: true,
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan",
      "whole 30",
    ],
    occasions: [],
    extendedIngredients: [
      {
        id: 11233,
        aisle: "Produce",
        image: "kale.jpg",
        consistency: "solid",
        name: "kale",
        nameClean: "kale",
        original: "1 bunch kale",
        originalName: "kale",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
          metric: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "2 cloves garlic",
        originalName: "garlic",
        amount: 2.0,
        unit: "cloves",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 Tbsp olive oil",
        originalName: "olive oil",
        amount: 1.0,
        unit: "Tbsp",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 15.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Heat olive oil in a large skillet. Add minced garlic and cook until fragrant.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 2,
            step: "Add washed and chopped kale. Sauté until wilted and tender, about 5-7 minutes. Season with salt and pepper.",
            ingredients: [
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    instructions:
      "Heat oil, sauté garlic, add kale and cook until tender. Season to taste.",
  },
  {
    id: 716406,
    title: "Asparagus and Pea Soup: Real Convenience Food",
    image: "https://img.spoonacular.com/recipes/716406-556x370.jpg",
    imageType: "jpg",
    servings: 2,
    readyInMinutes: 20,
    sourceUrl:
      "https://www.foodista.com/recipe/6Y7C5F5R/asparagus-and-pea-soup-real-convenience-food",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-716406",
    aggregateLikes: 44,
    healthScore: 100,
    spoonacularScore: 99.0,
    pricePerServing: 176.45,
    cheap: false,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: "no",
    ketogenic: false,
    whole30: true,
    cuisines: [],
    dishTypes: ["soup", "lunch", "main course", "main dish", "dinner"],
    diets: [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan",
      "whole 30",
    ],
    occasions: [],
    extendedIngredients: [
      {
        id: 11011,
        aisle: "Produce",
        image: "asparagus.png",
        consistency: "solid",
        name: "asparagus",
        nameClean: "asparagus",
        original: "1 bunch asparagus",
        originalName: "asparagus",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
          metric: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
        },
      },
      {
        id: 11304,
        aisle: "Produce",
        image: "peas.jpg",
        consistency: "solid",
        name: "peas",
        nameClean: "peas",
        original: "1 cup frozen peas",
        originalName: "frozen peas",
        amount: 1.0,
        unit: "cup",
        meta: ["frozen"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 145.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "liquid",
        name: "vegetable broth",
        nameClean: "vegetable broth",
        original: "2 cups vegetable broth",
        originalName: "vegetable broth",
        amount: 2.0,
        unit: "cups",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 480.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Sauté chopped onion and garlic in a pot. Add asparagus, peas, and broth. Simmer until vegetables are tender.",
            ingredients: [],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Blend until smooth. Adjust seasoning and serve.",
            ingredients: [],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
        ],
      },
    ],
    instructions: "Cook vegetables in broth, blend until smooth, and season.",
  },
  {
    id: 715497,
    title: "Berry Banana Breakfast Smoothie",
    image: "https://img.spoonacular.com/recipes/715497-556x370.jpg",
    imageType: "jpg",
    servings: 1,
    readyInMinutes: 5,
    sourceUrl: "https://www.pinkwhen.com/berry-banana-breakfast-smoothie/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-715497",
    aggregateLikes: 87,
    healthScore: 64,
    spoonacularScore: 96.0,
    pricePerServing: 157.89,
    cheap: false,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: [],
    dishTypes: ["morning meal", "brunch", "breakfast", "beverage", "drink"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    extendedIngredients: [
      {
        id: 9040,
        aisle: "Produce",
        image: "bananas.jpg",
        consistency: "solid",
        name: "banana",
        nameClean: "banana",
        original: "1 frozen banana",
        originalName: "frozen banana",
        amount: 1.0,
        unit: "",
        meta: ["frozen"],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9050,
        aisle: "Produce",
        image: "blueberries.jpg",
        consistency: "solid",
        name: "blueberries",
        nameClean: "blueberries",
        original: "1/2 cup frozen blueberries",
        originalName: "frozen blueberries",
        amount: 0.5,
        unit: "cup",
        meta: ["frozen"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 75.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1085,
        aisle: "Milk, Eggs, Other Dairy",
        image: "milk.png",
        consistency: "liquid",
        name: "milk",
        nameClean: "milk",
        original: "1 cup milk",
        originalName: "milk",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 244.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Add all ingredients to a blender and blend until smooth.",
            ingredients: [],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
        ],
      },
    ],
    instructions: "Blend banana, berries, and milk until smooth.",
  },
  {
    id: 716381,
    title: "Nigerian Snail Stew",
    image: "https://img.spoonacular.com/recipes/716381-556x370.jpg",
    imageType: "jpg",
    servings: 1,
    readyInMinutes: 45,
    sourceUrl: "https://www.afrolems.com/2014/05/26/nigerian-snail-stew/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/nigerian-snail-stew-716381",
    aggregateLikes: 12,
    healthScore: 39,
    spoonacularScore: 78.0,
    pricePerServing: 528.67,
    cheap: false,
    creditsText: "Afrolems",
    license: null,
    sourceName: "Afrolems",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 19,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["african"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    extendedIngredients: [
      {
        id: 90560,
        aisle: "Meat",
        image: "escargot.png",
        consistency: "solid",
        name: "snails",
        nameClean: "snails",
        original: "1 lb snails",
        originalName: "snails",
        amount: 1.0,
        unit: "lb",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "lb", unitLong: "pound" },
          metric: { amount: 453.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11529,
        aisle: "Produce",
        image: "tomato.png",
        consistency: "solid",
        name: "tomatoes",
        nameClean: "tomato",
        original: "4 tomatoes",
        originalName: "tomatoes",
        amount: 4.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "", unitLong: "" },
          metric: { amount: 4.0, unitShort: "", unitLong: "" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Clean and prepare the snails. Sauté with onions, peppers, and tomatoes until the stew thickens.",
            ingredients: [],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
        ],
      },
    ],
    instructions: "Prepare snails and cook in a rich tomato-pepper stew.",
  },
  {
    id: 782601,
    title: "Red Kidney Bean Jambalaya",
    image: "https://img.spoonacular.com/recipes/782601-556x370.jpg",
    imageType: "jpg",
    servings: 6,
    readyInMinutes: 45,
    sourceUrl:
      "https://www.foodista.com/recipe/M2KVC9P6/red-kidney-bean-jambalaya",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/red-kidney-bean-jambalaya-782601",
    aggregateLikes: 53,
    healthScore: 96,
    spoonacularScore: 99.0,
    pricePerServing: 91.28,
    cheap: true,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["cajun", "creole"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    extendedIngredients: [
      {
        id: 16033,
        aisle: "Canned and Jarred",
        image: "kidney-beans.jpg",
        consistency: "solid",
        name: "kidney beans",
        nameClean: "kidney beans",
        original: "2 cans red kidney beans",
        originalName: "red kidney beans",
        amount: 2.0,
        unit: "cans",
        meta: ["red"],
        measures: {
          us: { amount: 2.0, unitShort: "cans", unitLong: "cans" },
          metric: { amount: 2.0, unitShort: "cans", unitLong: "cans" },
        },
      },
      {
        id: 20040,
        aisle: "Pasta and Rice",
        image: "uncooked-brown-rice.png",
        consistency: "solid",
        name: "brown rice",
        nameClean: "brown rice",
        original: "1 cup brown rice",
        originalName: "brown rice",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 185.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Sauté the holy trinity (onion, celery, bell pepper). Add rice, beans, tomatoes, and spices. Simmer until rice is cooked.",
            ingredients: [],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Sauté vegetables, add rice, beans and seasonings, then simmer.",
  },
  {
    id: 715446,
    title: "Slow Cooker Beef Stew",
    image: "https://img.spoonacular.com/recipes/715446-556x370.jpg",
    imageType: "jpg",
    servings: 6,
    readyInMinutes: 490,
    sourceUrl: "https://www.pinkwhen.com/slow-cooker-beef-stew-recipe/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/slow-cooker-beef-stew-715446",
    aggregateLikes: 130,
    healthScore: 73,
    spoonacularScore: 97.0,
    pricePerServing: 285.67,
    cheap: false,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    ketogenic: false,
    whole30: true,
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "whole 30"],
    occasions: [],
    extendedIngredients: [
      {
        id: 23572,
        aisle: "Meat",
        image: "beef-cubes-raw.png",
        consistency: "solid",
        name: "beef stew meat",
        nameClean: "beef stew meat",
        original: "2 lbs beef stew meat",
        originalName: "beef stew meat",
        amount: 2.0,
        unit: "lbs",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "lbs", unitLong: "pounds" },
          metric: { amount: 907.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "solid",
        name: "carrots",
        nameClean: "carrots",
        original: "4 carrots",
        originalName: "carrots",
        amount: 4.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "", unitLong: "" },
          metric: { amount: 4.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11352,
        aisle: "Produce",
        image: "potatoes-yukon-gold.png",
        consistency: "solid",
        name: "potatoes",
        nameClean: "potatoes",
        original: "4 potatoes",
        originalName: "potatoes",
        amount: 4.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "", unitLong: "" },
          metric: { amount: 4.0, unitShort: "", unitLong: "" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Add all ingredients to the slow cooker. Cook on low for 8 hours.",
            ingredients: [],
            equipment: [
              {
                id: 404635,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Combine ingredients in slow cooker and cook on low for 8 hours.",
  },
  {
    id: 715415,
    title: "Red Lentil Soup with Chicken and Spinach",
    image: "https://img.spoonacular.com/recipes/715415-556x370.jpg",
    imageType: "jpg",
    servings: 4,
    readyInMinutes: 45,
    sourceUrl:
      "https://www.pinkwhen.com/red-lentil-soup-with-chicken-and-spinach/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/red-lentil-soup-with-chicken-and-spinach-715415",
    aggregateLikes: 11,
    healthScore: 100,
    spoonacularScore: 99.0,
    pricePerServing: 281.34,
    cheap: false,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: [],
    dishTypes: ["soup", "lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    extendedIngredients: [
      {
        id: 16069,
        aisle: "Pasta and Rice",
        image: "red-lentils.png",
        consistency: "solid",
        name: "red lentils",
        nameClean: "red lentils",
        original: "1 cup red lentils",
        originalName: "red lentils",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 192.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 5006,
        aisle: "Meat",
        image: "whole-chicken.jpg",
        consistency: "solid",
        name: "chicken",
        nameClean: "chicken",
        original: "2 cups cooked chicken",
        originalName: "cooked chicken",
        amount: 2.0,
        unit: "cups",
        meta: ["cooked"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 280.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 10011457,
        aisle: "Produce",
        image: "spinach.jpg",
        consistency: "solid",
        name: "spinach",
        nameClean: "spinach",
        original: "2 cups fresh spinach",
        originalName: "fresh spinach",
        amount: 2.0,
        unit: "cups",
        meta: ["fresh"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 60.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Sauté aromatics, add lentils and broth, simmer until tender. Stir in chicken and spinach at the end.",
            ingredients: [],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Cook lentils with aromatics, finish with chicken and spinach.",
  },
  {
    id: 716426,
    title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
    image: "https://img.spoonacular.com/recipes/716426-556x370.jpg",
    imageType: "jpg",
    servings: 8,
    readyInMinutes: 30,
    sourceUrl:
      "https://www.foodista.com/recipe/6B3X4W3G/cauliflower-brown-rice-and-vegetable-fried-rice",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-716426",
    aggregateLikes: 89,
    healthScore: 75,
    spoonacularScore: 97.0,
    pricePerServing: 112.32,
    cheap: true,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["chinese", "asian"],
    dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    extendedIngredients: [
      {
        id: 11135,
        aisle: "Produce",
        image: "cauliflower.jpg",
        consistency: "solid",
        name: "cauliflower",
        nameClean: "cauliflower",
        original: "1 head cauliflower, riced",
        originalName: "cauliflower",
        amount: 1.0,
        unit: "head",
        meta: ["riced"],
        measures: {
          us: { amount: 1.0, unitShort: "head", unitLong: "head" },
          metric: { amount: 1.0, unitShort: "head", unitLong: "head" },
        },
      },
      {
        id: 20040,
        aisle: "Pasta and Rice",
        image: "uncooked-brown-rice.png",
        consistency: "solid",
        name: "brown rice",
        nameClean: "brown rice",
        original: "2 cups cooked brown rice",
        originalName: "cooked brown rice",
        amount: 2.0,
        unit: "cups",
        meta: ["cooked"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 370.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Stir-fry riced cauliflower and vegetables. Add cooked brown rice and season with soy sauce or alternative.",
            ingredients: [],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Stir-fry cauliflower rice with vegetables and cooked brown rice.",
  },
  {
    id: 715421,
    title: "Cheesy Chicken Enchilada Quinoa Casserole",
    image: "https://img.spoonacular.com/recipes/715421-556x370.jpg",
    imageType: "jpg",
    servings: 4,
    readyInMinutes: 30,
    sourceUrl:
      "https://www.pinkwhen.com/cheesy-chicken-enchilada-quinoa-casserole/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/cheesy-chicken-enchilada-quinoa-casserole-715421",
    aggregateLikes: 39,
    healthScore: 45,
    spoonacularScore: 90.0,
    pricePerServing: 198.45,
    cheap: false,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 11,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["mexican"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free"],
    occasions: [],
    extendedIngredients: [
      {
        id: 20035,
        aisle: "Pasta and Rice",
        image: "uncooked-quinoa.png",
        consistency: "solid",
        name: "quinoa",
        nameClean: "quinoa",
        original: "1 cup quinoa",
        originalName: "quinoa",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 170.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 5006,
        aisle: "Meat",
        image: "whole-chicken.jpg",
        consistency: "solid",
        name: "chicken",
        nameClean: "chicken",
        original: "2 cups shredded chicken",
        originalName: "shredded chicken",
        amount: 2.0,
        unit: "cups",
        meta: ["shredded"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 280.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1001025,
        aisle: "Cheese",
        image: "shredded-cheese-white.jpg",
        consistency: "solid",
        name: "cheese",
        nameClean: "cheese",
        original: "1 cup shredded cheese",
        originalName: "shredded cheese",
        amount: 1.0,
        unit: "cup",
        meta: ["shredded"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 113.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Cook quinoa. Mix with chicken, enchilada sauce, and cheese. Bake until bubbly.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Combine cooked quinoa, chicken, sauce and cheese. Bake until melted and hot.",
  },
  {
    id: 716408,
    title: "Greek-Style Baked Fish: Fresh, Simple, and Delicious",
    image: "https://img.spoonacular.com/recipes/716408-556x370.jpg",
    imageType: "jpg",
    servings: 4,
    readyInMinutes: 30,
    sourceUrl:
      "https://www.foodista.com/recipe/K5Q3X4W3/greek-style-baked-fish-fresh-simple-and-delicious",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/greek-style-baked-fish-fresh-simple-and-delicious-716408",
    aggregateLikes: 21,
    healthScore: 62,
    spoonacularScore: 93.0,
    pricePerServing: 312.18,
    cheap: false,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: "no",
    ketogenic: false,
    whole30: true,
    cuisines: ["mediterranean", "greek"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "pescatarian", "whole 30"],
    occasions: [],
    extendedIngredients: [
      {
        id: 15076,
        aisle: "Seafood",
        image: "salmon.png",
        consistency: "solid",
        name: "fish fillets",
        nameClean: "fish fillets",
        original: "4 fish fillets",
        originalName: "fish fillets",
        amount: 4.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "", unitLong: "" },
          metric: { amount: 4.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "3 cloves garlic",
        originalName: "garlic",
        amount: 3.0,
        unit: "cloves",
        meta: [],
        measures: {
          us: { amount: 3.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 3.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 9159,
        aisle: "Produce",
        image: "lemon.jpg",
        consistency: "solid",
        name: "lemon",
        nameClean: "lemon",
        original: "1 lemon",
        originalName: "lemon",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Place fish in a baking dish. Top with garlic, lemon, olive oil, and herbs. Bake until fish flakes easily.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Season fish with garlic, lemon and olive oil. Bake until done.",
  },
  {
    id: 715424,
    title: "The Best Chili",
    image: "https://img.spoonacular.com/recipes/715424-556x370.jpg",
    imageType: "jpg",
    servings: 8,
    readyInMinutes: 130,
    sourceUrl: "https://www.pinkwhen.com/the-best-chili-recipe/",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/the-best-chili-715424",
    aggregateLikes: 65,
    healthScore: 38,
    spoonacularScore: 86.0,
    pricePerServing: 143.67,
    cheap: true,
    creditsText: "Pink When",
    license: null,
    sourceName: "Pink When",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: ["american"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    extendedIngredients: [
      {
        id: 10023572,
        aisle: "Meat",
        image: "beef-cubes-raw.png",
        consistency: "solid",
        name: "ground beef",
        nameClean: "ground beef",
        original: "2 lbs ground beef",
        originalName: "ground beef",
        amount: 2.0,
        unit: "lbs",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "lbs", unitLong: "pounds" },
          metric: { amount: 907.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 16015,
        aisle: "Canned and Jarred",
        image: "black-beans.jpg",
        consistency: "solid",
        name: "black beans",
        nameClean: "black beans",
        original: "2 cans black beans",
        originalName: "black beans",
        amount: 2.0,
        unit: "cans",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cans", unitLong: "cans" },
          metric: { amount: 2.0, unitShort: "cans", unitLong: "cans" },
        },
      },
      {
        id: 11529,
        aisle: "Produce",
        image: "tomato.png",
        consistency: "solid",
        name: "tomatoes",
        nameClean: "tomatoes",
        original: "1 can diced tomatoes",
        originalName: "diced tomatoes",
        amount: 1.0,
        unit: "can",
        meta: ["diced"],
        measures: {
          us: { amount: 1.0, unitShort: "can", unitLong: "can" },
          metric: { amount: 1.0, unitShort: "can", unitLong: "can" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Brown the beef. Add beans, tomatoes, and spices. Simmer for at least 1 hour.",
            ingredients: [],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions:
      "Brown meat, add remaining ingredients, and simmer until flavors meld.",
  },
  {
    id: 716432,
    title: "Finger Foods: Frittata Muffins",
    image: "https://img.spoonacular.com/recipes/716432-556x370.jpg",
    imageType: "jpg",
    servings: 6,
    readyInMinutes: 45,
    sourceUrl:
      "https://www.foodista.com/recipe/2X8K3P4W/finger-foods-frittata-muffins",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/finger-foods-frittata-muffins-716432",
    aggregateLikes: 8,
    healthScore: 32,
    spoonacularScore: 79.0,
    pricePerServing: 87.45,
    cheap: true,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: "no",
    ketogenic: false,
    whole30: false,
    cuisines: [],
    dishTypes: [
      "morning meal",
      "brunch",
      "breakfast",
      "fingerfood",
      "appetizer",
      "snack",
    ],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    extendedIngredients: [
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "solid",
        name: "eggs",
        nameClean: "eggs",
        original: "8 eggs",
        originalName: "eggs",
        amount: 8.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 8.0, unitShort: "", unitLong: "" },
          metric: { amount: 8.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11260,
        aisle: "Produce",
        image: "mushrooms.png",
        consistency: "solid",
        name: "mushrooms",
        nameClean: "mushrooms",
        original: "1 cup sliced mushrooms",
        originalName: "sliced mushrooms",
        amount: 1.0,
        unit: "cup",
        meta: ["sliced"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 70.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1001025,
        aisle: "Cheese",
        image: "shredded-cheese-white.jpg",
        consistency: "solid",
        name: "cheese",
        nameClean: "cheese",
        original: "1/2 cup shredded cheese",
        originalName: "shredded cheese",
        amount: 0.5,
        unit: "cup",
        meta: ["shredded"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 56.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Whisk eggs with vegetables and cheese. Pour into muffin tin and bake until set.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
              {
                id: 404648,
                name: "muffin tin",
                localizedName: "muffin tin",
                image: "muffin-tray.jpg",
              },
            ],
          },
        ],
      },
    ],
    instructions: "Mix eggs with fillings, pour into muffin cups, and bake.",
  },
  {
    id: 715437,
    title: "Chilled Cucumber Avocado Soup",
    image: "https://img.spoonacular.com/recipes/715437-556x370.jpg",
    imageType: "jpg",
    servings: 4,
    readyInMinutes: 15,
    sourceUrl:
      "https://www.foodista.com/recipe/8Y7C5F5R/chilled-cucumber-avocado-soup",
    spoonacularSourceUrl:
      "https://spoonacular.com/recipes/chilled-cucumber-avocado-soup-715437",
    aggregateLikes: 15,
    healthScore: 58,
    spoonacularScore: 91.0,
    pricePerServing: 156.78,
    cheap: false,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: "no",
    ketogenic: false,
    whole30: true,
    cuisines: [],
    dishTypes: [
      "soup",
      "lunch",
      "main course",
      "main dish",
      "dinner",
      "starter",
    ],
    diets: [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan",
      "whole 30",
    ],
    occasions: [],
    extendedIngredients: [
      {
        id: 11206,
        aisle: "Produce",
        image: "cucumber.jpg",
        consistency: "solid",
        name: "cucumber",
        nameClean: "cucumber",
        original: "2 cucumbers",
        originalName: "cucumbers",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "avocado",
        original: "2 avocados",
        originalName: "avocados",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "liquid",
        name: "vegetable broth",
        nameClean: "vegetable broth",
        original: "2 cups vegetable broth",
        originalName: "vegetable broth",
        amount: 2.0,
        unit: "cups",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 480.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Blend cucumber, avocado, broth, and seasonings until smooth. Chill before serving.",
            ingredients: [],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
        ],
      },
    ],
    instructions: "Blend all ingredients until smooth and chill.",
  },
];
