export const mockRecipes = [
  {
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    image: "https://img.spoonacular.com/recipes/716429-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 15,
    gaps: "no",
    preparationMinutes: 15,
    cookingMinutes: 30,
    aggregateLikes: 209,
    healthScore: 76,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 163.15,
    summary:
      "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be just the main course you are searching for...",
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["lacto ovo vegetarian"],
    occasions: [],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 584.39, unit: "kcal" },
        { name: "Fat", amount: 19.51, unit: "g" },
        { name: "Saturated Fat", amount: 3.48, unit: "g" },
        { name: "Carbohydrates", amount: 84.32, unit: "g" },
        { name: "Net Carbohydrates", amount: 73.29, unit: "g" },
        { name: "Sugar", amount: 7.31, unit: "g" },
        { name: "Cholesterol", amount: 5.67, unit: "mg" },
        { name: "Sodium", amount: 437.32, unit: "mg" },
        { name: "Protein", amount: 19.45, unit: "g" },
      ],
    },
  },
  {
    id: 715538,
    title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
    image: "https://img.spoonacular.com/recipes/715538-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 35,
    servings: 4,
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    healthScore: 42,
    pricePerServing: 245.12,
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 512.4, unit: "kcal" },
        { name: "Fat", amount: 22.1, unit: "g" },
        { name: "Carbohydrates", amount: 48.3, unit: "g" },
        { name: "Protein", amount: 31.8, unit: "g" },
      ],
    },
  },
  {
    id: 716381,
    title: "Nigerian Snail Stew",
    image: "https://img.spoonacular.com/recipes/716381-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 45,
    servings: 1,
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    healthScore: 88,
    pricePerServing: 312.5,
    cuisines: ["African"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "paleolithic", "primal"],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 298.7, unit: "kcal" },
        { name: "Fat", amount: 14.2, unit: "g" },
        { name: "Carbohydrates", amount: 12.4, unit: "g" },
        { name: "Protein", amount: 28.9, unit: "g" },
      ],
    },
  },
  {
    id: 715497,
    title: "Berry Banana Breakfast Smoothie",
    image: "https://img.spoonacular.com/recipes/715497-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 5,
    servings: 1,
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    healthScore: 95,
    pricePerServing: 98.4,
    cuisines: [],
    dishTypes: ["morning meal", "brunch", "breakfast"],
    diets: ["lacto ovo vegetarian", "gluten free"],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 312.5, unit: "kcal" },
        { name: "Fat", amount: 4.8, unit: "g" },
        { name: "Carbohydrates", amount: 58.2, unit: "g" },
        { name: "Protein", amount: 12.1, unit: "g" },
      ],
    },
  },
  {
    id: 715415,
    title: "Red Lentil Soup with Chicken and Turnips",
    image: "https://img.spoonacular.com/recipes/715415-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 55,
    servings: 8,
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    healthScore: 100,
    pricePerServing: 176.8,
    cuisines: [],
    dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 268.3, unit: "kcal" },
        { name: "Fat", amount: 7.9, unit: "g" },
        { name: "Carbohydrates", amount: 32.1, unit: "g" },
        { name: "Protein", amount: 18.4, unit: "g" },
      ],
    },
  },
  {
    id: 716406,
    title: "Asparagus and Pea Soup: Real Convenience Food",
    image: "https://img.spoonacular.com/recipes/716406-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 20,
    servings: 2,
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    healthScore: 100,
    pricePerServing: 214.6,
    cuisines: [],
    dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 189.4, unit: "kcal" },
        { name: "Fat", amount: 8.2, unit: "g" },
        { name: "Carbohydrates", amount: 22.7, unit: "g" },
        { name: "Protein", amount: 8.9, unit: "g" },
      ],
    },
  },
  {
    id: 644387,
    title: "Garlicky Kale",
    image: "https://img.spoonacular.com/recipes/644387-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 45,
    servings: 2,
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    healthScore: 100,
    pricePerServing: 69.3,
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan",
      "paleolithic",
      "primal",
    ],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 112.8, unit: "kcal" },
        { name: "Fat", amount: 8.1, unit: "g" },
        { name: "Carbohydrates", amount: 9.4, unit: "g" },
        { name: "Protein", amount: 3.7, unit: "g" },
      ],
    },
  },
  {
    id: 715446,
    title: "Slow Cooker Beef Stew",
    image: "https://img.spoonacular.com/recipes/715446-556x370.jpg",
    imageType: "jpg",
    readyInMinutes: 490,
    servings: 6,
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    healthScore: 73,
    pricePerServing: 298.7,
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    nutrition: {
      nutrients: [
        { name: "Calories", amount: 434.2, unit: "kcal" },
        { name: "Fat", amount: 16.8, unit: "g" },
        { name: "Carbohydrates", amount: 28.5, unit: "g" },
        { name: "Protein", amount: 41.3, unit: "g" },
      ],
    },
  },
];
